# Example 6
#
# Pulling out all the stops with cluster of seven Vagrant boxes.
#
domain   = 'example.com'

nodes = [
  { :hostname => 'webserver1',   :ip => '192.168.0.42', :box => 'xenial64', :ram => '512' },
  { :hostname => 'webserver2',   :ip => '192.168.0.43', :box => 'xenial64', :ram => '512' },
  { :hostname => 'webserver3',   :ip => '192.168.0.44', :box => 'xenial64', :ram => '512' },
  { :hostname => 'webserver4',   :ip => '192.168.0.45', :box => 'xenial64', :ram => '512' },

]

Vagrant.configure("2") do |config|
  nodes.each do |node|
    config.vm.define node[:hostname] do |nodeconfig|
      nodeconfig.vm.box = [:box]
      nodeconfig.vm.hostname = node[:hostname] + ".box"
      nodeconfig.vm.network :private_network, ip: node[:ip]
      memory = node[:ram] ? node[:ram] : 512;

    #  nodeconfig.vm.provider :virtualbox do |vb|
    #    vb.customize [
    #      "modifyvm", :id,
    #      "--cpuexecutioncap", "50",
    #      "--memory", memory.to_s,
    #    ]
    #  end

    end
  end
end
